### ISSUE TITLE
Контекст принимает решение с использованием angle bracket type assertion

### ISSUE THREAD

**Issue by Ulisseus** [nikalexxx/ts-homework#3]
Из описания задания: 
`as запрещён`

И если попытаться использовать `as`, например, отослать что-нибудь вроде кода ниже:
```ts
const colors={
    red:'red',
    green:'green'
}

type  Colors = keyof typeof colors;
const colorKeys = Object.keys(colors) as Colors
```
То решение не будет принято. 

Но если использовать аналогичный синтакс с угловыми скобками, то решение уже валидное. 
```ts
const colors={
    red:'red',
    green:'green'
}

type  Colors = keyof typeof colors;
const colorKeys = <Colors>Object.keys(colors)
```

Не уверен, что так было задумано.

**Comment by nikalexxx** [comment]
Простой проверкой текста такое решение не отловить, так что в текущей версии это остаётся на совести решающих.
